export type V2ReservationStatus =
  | "pending"
  | "confirmed"
  | "completed"
  | "cancelled"
  | "no_show";

export type V2ClientStatus =
  | "new"
  | "active"
  | "frequent"
  | "inactive"
  | "no_show";

export type V2DeliveryStatus = "confirmed" | "completed" | "cancelled";
export type V2DeliveryType = "delivery" | "pickup";

export const v2CurrentLocal = {
  name: "Demuru",
  subtitle: "Panel del local",
  publicUrl: "demuru.tangoreservas.com",
  owner: "Mariano",
  role: "Dueño",
};

export const v2Reservations = [
  {
    id: "res-1",
    date: "2026-07-02",
    time: "19:00",
    client: "María López",
    people: 2,
    phone: "11 2345 6789",
    email: "maria@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Ventana",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-2",
    date: "2026-07-02",
    time: "19:30",
    client: "Carlos Gómez",
    people: 3,
    phone: "11 4567 1209",
    email: "carlos@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "—",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-3",
    date: "2026-07-02",
    time: "20:15",
    client: "Lucía Fernández",
    people: 2,
    phone: "11 9988 2345",
    email: "lucia@email.com",
    durationMinutes: 120,
    tableName: "Mesa 3",
    note: "Sin gluten",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-4",
    date: "2026-07-02",
    time: "21:00",
    client: "Juan Pérez",
    people: 4,
    phone: "11 2233 4455",
    email: "juan@email.com",
    durationMinutes: 120,
    tableName: "Mesa 12",
    note: "Mesa 12",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-5",
    date: "2026-07-02",
    time: "21:30",
    client: "Ana Rodríguez",
    people: 2,
    phone: "11 7654 3201",
    email: "ana@email.com",
    durationMinutes: 120,
    tableName: "Mesa 8",
    note: "Aniversario",
    status: "completed" as V2ReservationStatus,
  },
  {
    id: "res-6",
    date: "2026-07-02",
    time: "22:00",
    client: "Martín Sosa",
    people: 2,
    phone: "11 5566 7788",
    email: "martin@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "—",
    status: "cancelled" as V2ReservationStatus,
  },
  {
    id: "res-7",
    date: "2026-07-02",
    time: "22:30",
    client: "Sofía Martínez",
    people: 3,
    phone: "11 6677 8899",
    email: "sofia@email.com",
    durationMinutes: 120,
    tableName: "Mesa 4",
    note: "Sin lactosa",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-8",
    date: "2026-07-02",
    time: "23:00",
    client: "Diego Ramírez",
    people: 2,
    phone: "11 3344 5566",
    email: "diego@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Exterior",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-9",
    date: "2026-07-03",
    time: "19:15",
    client: "Valentina Costa",
    people: 4,
    phone: "11 7788 9900",
    email: "valentina@email.com",
    durationMinutes: 120,
    tableName: "Mesa 6",
    note: "Cumpleaños",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-10",
    date: "2026-07-03",
    time: "20:00",
    client: "Federico Ruiz",
    people: 2,
    phone: "11 1122 3344",
    email: "federico@email.com",
    durationMinutes: 120,
    tableName: "Mesa 2",
    note: "—",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-11",
    date: "2026-07-03",
    time: "20:30",
    client: "Camila Torres",
    people: 3,
    phone: "11 4455 6677",
    email: "camila@email.com",
    durationMinutes: 120,
    tableName: "Mesa 10",
    note: "Sin TACC",
    status: "completed" as V2ReservationStatus,
  },
  {
    id: "res-12",
    date: "2026-07-03",
    time: "21:00",
    client: "Nicolás Herrera",
    people: 2,
    phone: "11 8899 0011",
    email: "nicolas@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Mesa tranquila",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-13",
    date: "2026-07-03",
    time: "21:45",
    client: "Agustina Molina",
    people: 5,
    phone: "11 9090 1122",
    email: "agustina@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Terraza",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-14",
    date: "2026-07-03",
    time: "22:30",
    client: "Tomás Medina",
    people: 2,
    phone: "11 1212 3434",
    email: "tomas@email.com",
    durationMinutes: 120,
    tableName: "Mesa 5",
    note: "—",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-15",
    date: "2026-07-04",
    time: "18:45",
    client: "Florencia Suárez",
    people: 2,
    phone: "11 5656 7878",
    email: "florencia@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Aniversario",
    status: "cancelled" as V2ReservationStatus,
  },
  {
    id: "res-16",
    date: "2026-07-04",
    time: "19:30",
    client: "Gonzalo Peralta",
    people: 6,
    phone: "11 3434 5656",
    email: "gonzalo@email.com",
    durationMinutes: 120,
    tableName: "Mesa grande",
    note: "Mesa grande",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-17",
    date: "2026-07-04",
    time: "20:00",
    client: "Paula Benítez",
    people: 2,
    phone: "11 4141 5252",
    email: "paula@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Cerca de la entrada",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-18",
    date: "2026-07-04",
    time: "21:15",
    client: "Sebastián Luna",
    people: 4,
    phone: "11 6363 7474",
    email: "sebastian@email.com",
    durationMinutes: 120,
    tableName: "Mesa 3",
    note: "Cumpleaños",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-19",
    date: "2026-07-04",
    time: "22:15",
    client: "Julieta Navarro",
    people: 3,
    phone: "11 8585 9696",
    email: "julieta@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Sin maní",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-20",
    date: "2026-07-05",
    time: "12:30",
    client: "Emiliano Duarte",
    people: 2,
    phone: "11 1010 2020",
    email: "emiliano@email.com",
    durationMinutes: 90,
    tableName: "",
    note: "Mesa interior",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-21",
    date: "2026-07-05",
    time: "13:15",
    client: "Carla Ibarra",
    people: 5,
    phone: "11 3030 4040",
    email: "carla@email.com",
    durationMinutes: 90,
    tableName: "",
    note: "Grupo de amigos",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-22",
    date: "2026-07-05",
    time: "14:00",
    client: "Ramiro Acosta",
    people: 2,
    phone: "11 5050 6060",
    email: "ramiro@email.com",
    durationMinutes: 90,
    tableName: "",
    note: "Prefiere silencio",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-23",
    date: "2026-07-05",
    time: "15:00",
    client: "Micaela Ríos",
    people: 4,
    phone: "11 7070 8080",
    email: "micaela@email.com",
    durationMinutes: 90,
    tableName: "Mesa 7",
    note: "Almuerzo familiar",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-24",
    date: "2026-07-06",
    time: "19:00",
    client: "Bruno Leiva",
    people: 2,
    phone: "11 2222 3333",
    email: "bruno@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Primera vez",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-25",
    date: "2026-07-06",
    time: "19:45",
    client: "Daniela Vega",
    people: 3,
    phone: "11 4444 5555",
    email: "daniela@email.com",
    durationMinutes: 120,
    tableName: "Mesa 9",
    note: "Vegetariana",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-26",
    date: "2026-07-06",
    time: "20:30",
    client: "Hernán Ponce",
    people: 4,
    phone: "11 6666 7777",
    email: "hernan@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Cerca de ventana",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-27",
    date: "2026-07-06",
    time: "22:00",
    client: "Laura Méndez",
    people: 2,
    phone: "11 8888 9999",
    email: "laura@email.com",
    durationMinutes: 120,
    tableName: "Mesa 1",
    note: "—",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-28",
    date: "2026-07-07",
    time: "18:30",
    client: "Pablo Roldán",
    people: 6,
    phone: "11 1313 1414",
    email: "pablo@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Grupo grande",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-29",
    date: "2026-07-07",
    time: "19:30",
    client: "Natalia Ferreyra",
    people: 2,
    phone: "11 1515 1616",
    email: "natalia@email.com",
    durationMinutes: 120,
    tableName: "Mesa 4",
    note: "Sin lactosa",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-30",
    date: "2026-07-07",
    time: "20:15",
    client: "Iván Morales",
    people: 3,
    phone: "11 1717 1818",
    email: "ivan@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Cumpleaños",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-31",
    date: "2026-07-07",
    time: "21:00",
    client: "Rocío Alvarez",
    people: 2,
    phone: "11 1919 2020",
    email: "rocio@email.com",
    durationMinutes: 120,
    tableName: "Mesa 8",
    note: "—",
    status: "completed" as V2ReservationStatus,
  },
  {
    id: "res-32",
    date: "2026-07-08",
    time: "19:15",
    client: "Mateo Silva",
    people: 2,
    phone: "11 2121 2222",
    email: "mateo@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "Mesa tranquila",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-33",
    date: "2026-07-08",
    time: "20:00",
    client: "Clara Núñez",
    people: 4,
    phone: "11 2323 2424",
    email: "clara@email.com",
    durationMinutes: 120,
    tableName: "Mesa 11",
    note: "Sin gluten",
    status: "confirmed" as V2ReservationStatus,
  },
  {
    id: "res-34",
    date: "2026-07-08",
    time: "20:45",
    client: "Oscar Cabrera",
    people: 2,
    phone: "11 2525 2626",
    email: "oscar@email.com",
    durationMinutes: 120,
    tableName: "",
    note: "—",
    status: "pending" as V2ReservationStatus,
  },
  {
    id: "res-35",
    date: "2026-07-08",
    time: "22:15",
    client: "Elena Prieto",
    people: 5,
    phone: "11 2727 2828",
    email: "elena@email.com",
    durationMinutes: 120,
    tableName: "Mesa 6",
    note: "Aniversario",
    status: "confirmed" as V2ReservationStatus,
  },
];

export const v2Deliveries = [
  {
    id: "env-1",
    time: "19:05",
    client: "María López",
    phone: "11 2345 6789",
    address: "Av. Bunge 1234",
    deliveryType: "delivery" as V2DeliveryType,
    order:
      "2 pizzas muzzarella grandes, 1 fainá, 1 gaseosa cola 1.5L y 6 empanadas de carne cortada a cuchillo",
    total: 28500,
    payment: "Efectivo",
    note: "Tocar timbre 2B. Llevar cambio para $30.000.",
    status: "confirmed" as V2DeliveryStatus,
  },
  {
    id: "env-2",
    time: "19:20",
    client: "Carlos Gómez",
    phone: "11 4567 1209",
    address: "Retira en local",
    deliveryType: "pickup" as V2DeliveryType,
    order: "12 empanadas surtidas: 4 carne, 4 jamón y queso, 2 pollo, 2 humita",
    total: 14400,
    payment: "Transferencia",
    note: "Sin picante. Pasa a retirar a nombre de Carlos.",
    status: "confirmed" as V2DeliveryStatus,
  },
  {
    id: "env-3",
    time: "19:45",
    client: "Lucía Fernández",
    phone: "11 9988 2345",
    address: "Libertador 220",
    deliveryType: "delivery" as V2DeliveryType,
    order: "1 fugazzeta grande, 6 empanadas de verdura, 6 empanadas de pollo",
    total: 17600,
    payment: "Tarjeta",
    note: "Cliente frecuente. Avisar antes de salir.",
    status: "completed" as V2DeliveryStatus,
  },
  {
    id: "env-4",
    time: "20:10",
    client: "Juan Pérez",
    phone: "11 2233 4455",
    address: "Marco Polo 560",
    deliveryType: "delivery" as V2DeliveryType,
    order: "2 napolitanas grandes, 1 porción de papas, 1 gaseosa lima limón",
    total: 25000,
    payment: "Efectivo",
    note: "Llevar cambio. Casa del fondo.",
    status: "confirmed" as V2DeliveryStatus,
  },
  {
    id: "env-5",
    time: "20:35",
    client: "Ana Rodríguez",
    phone: "11 7654 3201",
    address: "Retira en local",
    deliveryType: "pickup" as V2DeliveryType,
    order: "24 empanadas + 2 gaseosas: 8 carne, 8 pollo, 8 jamón y queso",
    total: 32600,
    payment: "Transferencia",
    note: "Casa con portón negro. Retira otra persona.",
    status: "completed" as V2DeliveryStatus,
  },
  {
    id: "env-6",
    time: "21:00",
    client: "Martín Sosa",
    phone: "11 5566 7788",
    address: "Bunge 1500",
    deliveryType: "delivery" as V2DeliveryType,
    order: "1 calabresa grande + 1 provolone grande",
    total: 22500,
    payment: "Efectivo",
    note: "Canceló por demora",
    status: "cancelled" as V2DeliveryStatus,
  },
  {
    id: "env-7",
    time: "21:20",
    client: "Sofía Martínez",
    phone: "11 6677 8899",
    address: "Del Tuyú 440",
    deliveryType: "delivery" as V2DeliveryType,
    order: "3 pizzas chicas: muzzarella, especial y roquefort",
    total: 24000,
    payment: "Tarjeta",
    note: "Entregar en recepción",
    status: "confirmed" as V2DeliveryStatus,
  },
  {
    id: "env-8",
    time: "21:45",
    client: "Diego Ramírez",
    phone: "11 3344 5566",
    address: "Retira en local",
    deliveryType: "pickup" as V2DeliveryType,
    order: "18 empanadas: 6 carne, 6 pollo, 6 caprese",
    total: 21600,
    payment: "Efectivo",
    note: "—",
    status: "confirmed" as V2DeliveryStatus,
  },
  {
    id: "env-9",
    time: "22:10",
    client: "Valentina Costa",
    phone: "11 7788 9900",
    address: "Intermédanos 710",
    deliveryType: "delivery" as V2DeliveryType,
    order: "1 muzzarella grande + 1 especial grande + 1 fainá",
    total: 19800,
    payment: "Transferencia",
    note: "Departamento 4",
    status: "completed" as V2DeliveryStatus,
  },
  {
    id: "env-10",
    time: "22:30",
    client: "Federico Ruiz",
    phone: "11 1122 3344",
    address: "Jason 1030",
    deliveryType: "delivery" as V2DeliveryType,
    order: "6 empanadas + 1 pizza individual de jamón y morrones",
    total: 11200,
    payment: "Efectivo",
    note: "Sin aceitunas",
    status: "confirmed" as V2DeliveryStatus,
  },
];

export const v2Clients = [
  {
    id: "cli-1",
    name: "María López",
    initials: "ML",
    phone: "11 2345 6789",
    email: "maria@email.com",
    lastVisit: "10 may 2025",
    reservations: 6,
    preference: "Ventana",
    status: "frequent" as V2ClientStatus,
    note: "Prefiere sentarse cerca de la ventana.",
  },
  {
    id: "cli-2",
    name: "Juan Pérez",
    initials: "JP",
    phone: "11 2233 4455",
    email: "juan@email.com",
    lastVisit: "15 may 2025",
    reservations: 4,
    preference: "Mesa 12",
    status: "active" as V2ClientStatus,
    note: "",
  },
  {
    id: "cli-3",
    name: "Lucía Fernández",
    initials: "LF",
    phone: "11 9988 2345",
    email: "lucia@email.com",
    lastVisit: "03 may 2025",
    reservations: 3,
    preference: "Sin gluten",
    status: "active" as V2ClientStatus,
    note: "Alergia declarada: gluten.",
  },
  {
    id: "cli-4",
    name: "Carlos Gómez",
    initials: "CG",
    phone: "11 4567 1209",
    email: "carlos@email.com",
    lastVisit: "27 abr 2025",
    reservations: 2,
    preference: "—",
    status: "new" as V2ClientStatus,
    note: "",
  },
  {
    id: "cli-5",
    name: "Diego Ramírez",
    initials: "DR",
    phone: "11 3344 5566",
    email: "diego@email.com",
    lastVisit: "30 abr 2025",
    reservations: 2,
    preference: "Exterior",
    status: "no_show" as V2ClientStatus,
    note: "Tuvo un no-show reciente.",
  },
];


export type V2MenuItemStatus = "available" | "paused";

export const v2MenuCategories = [
  {
    id: "cat-1",
    name: "Pizzas clásicas",
    description: "Muzzarella, napolitana, fugazzeta y variantes tradicionales.",
    order: 1,
    visible: true,
    active: true,
  },
  {
    id: "cat-2",
    name: "Pizzas especiales",
    description: "Sabores premium y combinaciones de la casa.",
    order: 2,
    visible: true,
    active: true,
  },
  {
    id: "cat-3",
    name: "Empanadas",
    description: "Empanadas al horno por unidad o docena.",
    order: 3,
    visible: true,
    active: true,
  },
  {
    id: "cat-4",
    name: "Bebidas",
    description: "Gaseosas, aguas y bebidas sin alcohol.",
    order: 4,
    visible: true,
    active: true,
  },
  {
    id: "cat-5",
    name: "Promos",
    description: "Combos y promociones destacadas.",
    order: 5,
    visible: false,
    active: true,
  },
];

export const v2MenuItems = [
  {
    id: "menu-1",
    imageUrl: "/mock/menu/pizza-muzzarella.jfif",
    name: "Pizza muzzarella grande",
    categoryId: "cat-1",
    description: "Salsa de tomate, muzzarella, aceitunas y orégano.",
    price: 9500,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: true,
  },
  {
    id: "menu-2",
    imageUrl: "/mock/menu/pizza-napolitana.jfif",
    name: "Pizza napolitana grande",
    categoryId: "cat-1",
    description: "Muzzarella, tomate natural, ajo, aceitunas y orégano.",
    price: 11200,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: false,
  },
  {
    id: "menu-3",
    imageUrl: "/mock/menu/fugazzeta.jfif",
    name: "Fugazzeta rellena",
    categoryId: "cat-2",
    description: "Masa casera, cebolla, doble muzzarella y relleno especial.",
    price: 14500,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: true,
  },
  {
    id: "menu-4",
    imageUrl: "/mock/menu/pizza-calabresa.jfif",
    name: "Pizza calabresa grande",
    categoryId: "cat-2",
    description: "Muzzarella, longaniza calabresa, ají molido y aceitunas.",
    price: 13200,
    status: "paused" as V2MenuItemStatus,
    visible: true,
    featured: false,
  },
  {
    id: "menu-5",
    imageUrl: "/mock/menu/empanada-carne.jfif",
    name: "Empanada carne cortada a cuchillo",
    categoryId: "cat-3",
    description: "Carne cortada a cuchillo, cebolla, morrón y huevo.",
    price: 1200,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: true,
  },
  {
    id: "menu-6",
    imageUrl: "/mock/menu/empanada-jamon-queso.jfif",
    name: "Empanada jamón y queso",
    categoryId: "cat-3",
    description: "Jamón cocido, muzzarella y masa al horno.",
    price: 1200,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: false,
  },
  {
    id: "menu-7",
    imageUrl: "/mock/menu/gaseosa-cola.jfif",
    name: "Gaseosa cola 1.5L",
    categoryId: "cat-4",
    description: "Botella de gaseosa cola 1.5 litros.",
    price: 2800,
    status: "available" as V2MenuItemStatus,
    visible: true,
    featured: false,
  },
  {
    id: "menu-8",
    imageUrl: "/mock/menu/combo-pizza-empanadas.jfif",
    name: "Combo pizza + 6 empanadas",
    categoryId: "cat-5",
    description: "Una pizza muzzarella grande y seis empanadas a elección.",
    price: 15500,
    status: "available" as V2MenuItemStatus,
    visible: false,
    featured: true,
  },
];


export const v2WebConfig = {
  status: "published",
  publicUrl: "demuru.tangoreservas.com",
  lastUpdated: "15 may 2025",
  activeSections: 5,
  heroTitle: "Sabores únicos, momentos inolvidables",
  heroSubtitle:
    "Cocina de autor con productos de estación, ambiente cálido y atención cercana.",
  heroEyebrow: "Cocina de autor",
  primaryButtonLabel: "Reservar ahora",
  secondaryButtonLabel: "Ver menú",
  businessName: "Demuru",
  description:
    "Cocina de autor con productos de estación. Sabores honestos, ambiente cálido y atención cercana.",
  address: "Av. Bunge 1234, Pinamar",
  phone: "223 123 4567",
  whatsapp: "223 123 4567",
  instagram: "@demuru.pinamar",
  showMenu: true,
  showReservations: true,
  showWhatsApp: true,
  showGallery: true,
  showMap: true,
};


export type V2StockUnit =
  | "kg"
  | "g"
  | "l"
  | "ml"
  | "unidad"
  | "botella"
  | "caja"
  | "paquete"
  | "bolsa"
  | "lata";

export type V2StockCategory =
  | "Verdulería"
  | "Carnicería"
  | "Almacén"
  | "Bebidas"
  | "Packaging"
  | "Lácteos";

export const v2StockProducts = [
  {
    id: "stock-1",
    supplier: "Congelados Costa",
    unitCost: 1200,
    name: "Papas congeladas",
    category: "Verdulería" as V2StockCategory,
    unit: "kg" as V2StockUnit,
    totalStock: 20,
    consumedBySales: 16.2,
    alertBelow: 5,
    lastUpdated: "15 may 2025",
    note: "Comprar bolsa de 20 kg cuando entre en bajo stock.",
  },
  {
    id: "stock-2",
    supplier: "Carnicería Don Julio",
    unitCost: 3900,
    name: "Carne picada",
    category: "Carnicería" as V2StockCategory,
    unit: "kg" as V2StockUnit,
    totalStock: 15,
    consumedBySales: 13.4,
    alertBelow: 2,
    lastUpdated: "15 may 2025",
    note: "Proveedor habitual: carnicería local.",
  },
  {
    id: "stock-3",
    supplier: "Molino Atlántico",
    unitCost: 750,
    name: "Harina 000",
    category: "Almacén" as V2StockCategory,
    unit: "kg" as V2StockUnit,
    totalStock: 50,
    consumedBySales: 18,
    alertBelow: 10,
    lastUpdated: "14 may 2025",
    note: "Base para pizzas y empanadas.",
  },
  {
    id: "stock-4",
    supplier: "Lácteos del Sur",
    unitCost: 4200,
    name: "Muzzarella",
    category: "Lácteos" as V2StockCategory,
    unit: "kg" as V2StockUnit,
    totalStock: 30,
    consumedBySales: 24.5,
    alertBelow: 6,
    lastUpdated: "15 may 2025",
    note: "Mantener refrigerada.",
  },
  {
    id: "stock-5",
    supplier: "Distribuidora Bodega Norte",
    unitCost: 5200,
    name: "Vino Malbec",
    category: "Bebidas" as V2StockCategory,
    unit: "botella" as V2StockUnit,
    totalStock: 24,
    consumedBySales: 17,
    alertBelow: 6,
    lastUpdated: "13 may 2025",
    note: "Reponer por caja.",
  },
  {
    id: "stock-6",
    supplier: "Bebidas Pinamar",
    unitCost: 1500,
    name: "Gaseosa cola 1.5L",
    category: "Bebidas" as V2StockCategory,
    unit: "botella" as V2StockUnit,
    totalStock: 36,
    consumedBySales: 11,
    alertBelow: 8,
    lastUpdated: "15 may 2025",
    note: "Producto usado en envíos.",
  },
  {
    id: "stock-7",
    supplier: "Packaging Ruta 11",
    unitCost: 280,
    name: "Cajas de pizza grandes",
    category: "Packaging" as V2StockCategory,
    unit: "unidad" as V2StockUnit,
    totalStock: 120,
    consumedBySales: 97,
    alertBelow: 25,
    lastUpdated: "15 may 2025",
    note: "Packaging crítico para delivery.",
  },
  {
    id: "stock-8",
    supplier: "Almacén Mayorista Centro",
    unitCost: 2600,
    name: "Aceitunas",
    category: "Almacén" as V2StockCategory,
    unit: "kg" as V2StockUnit,
    totalStock: 8,
    consumedBySales: 8,
    alertBelow: 1.5,
    lastUpdated: "12 may 2025",
    note: "Sin stock. Reponer urgente.",
  },
];

export type V2LocalStatus = "active" | "draft" | "paused";
export type V2BusinessType = "restaurant" | "professional" | "beauty" | "other";
export type V2ReservationConfirmationMode = "manual" | "automatic";
export type V2NotificationChannel = "panel" | "email" | "whatsapp";
export type V2UserRole = "owner" | "manager" | "staff" | "support";

export const v2LocalSettings = {
  businessName: "Demuru",
  businessType: "restaurant" as V2BusinessType,
  publicUrl: "demuru.tangoreservas.com",
  status: "active" as V2LocalStatus,
  timezone: "America/Argentina/Buenos_Aires",
  description:
    "Cocina de autor con productos de estación. Sabores honestos, ambiente cálido y atención cercana.",
  address: "Av. Bunge 1234, Pinamar",
  phone: "223 123 4567",
  whatsapp: "223 123 4567",
  instagram: "@demuru.pinamar",
  email: "hola@demuru.com.ar",
  lastUpdated: "Hoy, 12:45",
  version: "v2.1.3",
};

export const v2BusinessHours = [
  { day: "Lunes", enabled: false, open: "Cerrado", close: "Cerrado" },
  { day: "Martes", enabled: true, open: "19:00", close: "00:30" },
  { day: "Miércoles", enabled: true, open: "19:00", close: "00:30" },
  { day: "Jueves", enabled: true, open: "19:00", close: "01:00" },
  { day: "Viernes", enabled: true, open: "19:00", close: "02:00" },
  { day: "Sábado", enabled: true, open: "19:00", close: "02:00" },
  { day: "Domingo", enabled: true, open: "12:00", close: "16:00" },
];

export const v2ReservationSettings = {
  enabled: true,
  standardDurationMinutes: 120,
  confirmationMode: "manual" as V2ReservationConfirmationMode,
  minimumNoticeHours: 2,
  bookingWindowDays: 14,
  maxPeoplePerSlot: 24,
  requiredFields: [
    "Nombre y apellido",
    "Teléfono",
    "Email",
    "Día",
    "Hora",
    "Cantidad de personas",
  ],
  optionalFields: ["Cumpleaños", "Preferencias", "Alergias", "Notas"],
};

export const v2DeliverySettings = {
  enabled: true,
  pickupEnabled: true,
  fixedDeliveryCost: 1200,
  minimumOrder: 8000,
  estimatedMinutes: 45,
  coverageZones: ["Pinamar centro", "Norte", "Ostende", "Valeria del Mar"],
  paymentMethods: ["Efectivo", "Transferencia", "Tarjeta"],
};

export const v2NotificationSettings = {
  newReservations: true,
  newDeliveries: true,
  lowStock: true,
  dailySummary: false,
  channels: ["panel", "email"] as V2NotificationChannel[],
};

export const v2LocalUsers = [
  {
    id: "user-1",
    name: "Mariano",
    email: "mariano@demuru.com.ar",
    role: "owner" as V2UserRole,
    status: "Activo",
  },
  {
    id: "user-2",
    name: "Encargado de turno",
    email: "turno@demuru.com.ar",
    role: "manager" as V2UserRole,
    status: "Activo",
  },
  {
    id: "user-3",
    name: "Soporte Tango",
    email: "soporte@tangoreservas.com",
    role: "support" as V2UserRole,
    status: "Soporte",
  },
];
